### ISSUE TITLE
I Nertivia.py crashed, I don't know how to possibly fix this

### ISSUE THREAD

**Issue by luqaska** [Nertivia-PY/Nertivia.py#29]
When I tried to start main.py, I had this error:
```Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import nertivia
  File "/home/runner/beepbot/venv/lib/python3.8/site-packages/nertivia/__init__.py", line 1, in <module>
    from .message import *
  File "/home/runner/beepbot/venv/lib/python3.8/site-packages/nertivia/message.py", line 2, in <module>
    import nertivia.bot
  File "/home/runner/beepbot/venv/lib/python3.8/site-packages/nertivia/bot.py", line 5, in <module>
    import socketioN
  File "/home/runner/beepbot/venv/lib/python3.8/site-packages/socketioN/__init__.py", line 5, in <module>
    from .asyncio_client import AsyncClient
  File "/home/runner/beepbot/venv/lib/python3.8/site-packages/socketioN/asyncio_client.py", line 8, in <module>
    import nertivia.cache_nertivia_data
  File "/home/runner/beepbot/venv/lib/python3.8/site-packages/nertivia/cache_nertivia_data.py", line 39, in <module>
    users: OrderedDict[str, User] = LimitedCache(maxsize=300)
TypeError: 'type' object is not subscriptable
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f22457ee370>```

**Comment by athyk** [comment]
Nertivia.py is currently in development.

I have changed it from socketio to using base WebSockets for more control. 

Should be fixed by the end of the month. Please keep an eye on the packages when it gets released

**Comment by luqaska** [comment]
> 

Ok
